version: "3"

services:
  discoplug:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "discoplug-bot"
    volumes:
      - type: bind
        source: "."
        target: "/deploy/discoplug"
        read_only: true
    environment:
      DISCOPLUG_TOKEN:  ${DISCOPLUG_TOKEN}

    entrypoint: python main.py
    restart: "always"
    tty: true
